## Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_selection import SelectKBest,chi2,f_classif
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier,VotingClassifier, AdaBoostClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.model_selection import cross_val_score,cross_val_predict,StratifiedKFold,train_test_split
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV
from imblearn.over_sampling import SMOTE,ADASYN
from imblearn.under_sampling import EditedNearestNeighbours
from sklearn.pipeline import Pipeline

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv(r'C:\Users\omdes\Desktop\data\teks\All_data_sets\Parkinsson disease.csv')

In [4]:
df.head()

name  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
0  phon_R01_S01_1      119.992       157.302        74.997         0.00784   
1  phon_R01_S01_2      122.400       148.650       113.819         0.00968   
2  phon_R01_S01_3      116.682       131.111       111.555         0.01050   
3  phon_R01_S01_4      116.676       137.871       111.366         0.00997   
4  phon_R01_S01_5      116.014       141.781       110.655         0.01284   

   MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  ...  \
0           0.00007   0.00370   0.00554     0.01109       0.04374  ...   
1           0.00008   0.00465   0.00696     0.01394       0.06134  ...   
2           0.00009   0.00544   0.00781     0.01633       0.05233  ...   
3           0.00009   0.00502   0.00698     0.01505       0.05492  ...   
4           0.00011   0.00655   0.00908     0.01966       0.06425  ...   

   Shimmer:DDA      NHR     HNR  status      RPDE       DFA   spread1  \
0      0.06545  0.02211  21.033       1  0.414783  0.815285 -4.813031   
1      0.09403  0.01929  19.085       1  0.458359  0.819521 -4.075192   
2      0.08270  0.01309  20.651       1  0.429895  0.825288 -4.443179   
3      0.08771  0.01353  20.644       1  0.434969  0.819235 -4.117501   
4      0.10470  0.01767  19.649       1  0.417356  0.823484 -3.747787   

    spread2        D2       PPE  
0  0.266482  2.301442  0.284654  
1  0.335590  2.486855  0.368674  
2  0.311173  2.342259  0.332634  
3  0.334147  2.405554  0.368975  
4  0.234513  2.332180  0.410335  

[5 rows x 24 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   name              195 non-null    object 
 1   MDVP:Fo(Hz)       195 non-null    float64
 2   MDVP:Fhi(Hz)      195 non-null    float64
 3   MDVP:Flo(Hz)      195 non-null    float64
 4   MDVP:Jitter(%)    195 non-null    float64
 5   MDVP:Jitter(Abs)  195 non-null    float64
 6   MDVP:RAP          195 non-null    float64
 7   MDVP:PPQ          195 non-null    float64
 8   Jitter:DDP        195 non-null    float64
 9   MDVP:Shimmer      195 non-null    float64
 10  MDVP:Shimmer(dB)  195 non-null    float64
 11  Shimmer:APQ3      195 non-null    float64
 12  Shimmer:APQ5      195 non-null    float64
 13  MDVP:APQ          195 non-null    float64
 14  Shimmer:DDA       195 non-null    float64
 15  NHR               195 non-null    float64
 16  HNR               195 non-null    float64
 1

In [6]:
df['name'].value_counts

<bound method IndexOpsMixin.value_counts of 0      phon_R01_S01_1
1      phon_R01_S01_2
2      phon_R01_S01_3
3      phon_R01_S01_4
4      phon_R01_S01_5
            ...      
190    phon_R01_S50_2
191    phon_R01_S50_3
192    phon_R01_S50_4
193    phon_R01_S50_5
194    phon_R01_S50_6
Name: name, Length: 195, dtype: object>

In [7]:
df['status'].value_counts()

status
1    147
0     48
Name: count, dtype: int64

In [8]:
x=df.drop(columns=['status','name'])
y=df['status']

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

## Using SelectKBest

In [51]:
dt=DecisionTreeClassifier()

scores_dic={}
for i in range(5,col):
    kbest=SelectKBest(f_classif,k=i)
    x_selected=kbest.fit_transform(x,y)
    scores = cross_val_score(estimator= dt,X=x_selected,y=y,cv=StratifiedKFold(5))
    scores_dic[i]=scores.mean()

In [42]:
top_5_scores = dict(sorted(scores_dic.items(), key=lambda item: item[1], reverse=True)[:5])

print("Top 5 accuracy scores:")
for k, v in top_5_scores.items():
    print(f"Number of features: {k}, Accuracy: {v}")


Top 5 accuracy scores:
Number of features: 11, Accuracy: 0.8153846153846154
Number of features: 7, Accuracy: 0.8102564102564103
Number of features: 10, Accuracy: 0.8102564102564103
Number of features: 8, Accuracy: 0.8051282051282052
Number of features: 15, Accuracy: 0.8


In [10]:
kbest=SelectKBest(f_classif,k=11)
kbest.fit_transform(x,y)

array([[ 1.199920e+02,  7.499700e+01,  4.374000e-02, ..., -4.813031e+00,
         2.664820e-01,  2.846540e-01],
       [ 1.224000e+02,  1.138190e+02,  6.134000e-02, ..., -4.075192e+00,
         3.355900e-01,  3.686740e-01],
       [ 1.166820e+02,  1.115550e+02,  5.233000e-02, ..., -4.443179e+00,
         3.111730e-01,  3.326340e-01],
       ...,
       [ 1.746880e+02,  7.428700e+01,  2.308000e-02, ..., -6.787197e+00,
         1.584530e-01,  1.317280e-01],
       [ 1.987640e+02,  7.490400e+01,  2.296000e-02, ..., -6.744577e+00,
         2.074540e-01,  1.233060e-01],
       [ 2.142890e+02,  7.797300e+01,  1.884000e-02, ..., -5.724056e+00,
         1.906670e-01,  1.485690e-01]])

In [11]:
kbest.get_support()

array([ True, False,  True, False, False, False, False, False,  True,
        True,  True,  True,  True, False, False,  True, False, False,
        True,  True, False,  True])

In [12]:
x_best_cols=x.columns[kbest.get_support()]

In [13]:
x_best_cols

Index(['MDVP:Fo(Hz)', 'MDVP:Flo(Hz)', 'MDVP:Shimmer', 'MDVP:Shimmer(dB)',
       'Shimmer:APQ3', 'Shimmer:APQ5', 'MDVP:APQ', 'HNR', 'spread1', 'spread2',
       'PPE'],
      dtype='object')

In [14]:
x=df[x_best_cols]

## Model Building

In [15]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [16]:
models=[LogisticRegression(),DecisionTreeClassifier(),RandomForestClassifier(),GaussianNB(),KNeighborsClassifier(),SVC(),XGBClassifier(),AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=1),n_estimators=50)]

In [17]:
for i in models:
    y_pred=cross_val_predict(estimator=i,X=x,y=y,cv=StratifiedKFold(5),n_jobs=-1)
    print(i)
    print('Confusion matrix:')
    print(confusion_matrix(y,y_pred))
    print('_ _ _ '*5)
    print('Classification Report:')
    print(classification_report(y,y_pred))
    print('_ _ _ '*15)

LogisticRegression()
Confusion matrix:
[[ 23  25]
 [ 11 136]]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Classification Report:
              precision    recall  f1-score   support

           0       0.68      0.48      0.56        48
           1       0.84      0.93      0.88       147

    accuracy                           0.82       195
   macro avg       0.76      0.70      0.72       195
weighted avg       0.80      0.82      0.80       195

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
DecisionTreeClassifier()
Confusion matrix:
[[ 23  25]
 [ 22 125]]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Classification Report:
              precision    recall  f1-score   support

           0       0.51      0.48      0.49        48
           1       0.83      0.85      0.84       147

    accuracy                           0.76       195
   macro avg       0.67      0.66      0.67       195
weighted avg       0.75      0.76      0.76       195

_ _ _ _ _ _ _ _ _ _

In [18]:
adasyn = SMOTE()
x_n, y_n = adasyn.fit_resample(x, y)

In [19]:
for i in models:
    y_pred=cross_val_predict(estimator=i,X=x_n,y=y_n,cv=StratifiedKFold(5),n_jobs=-1)
    print(i)
    print('Confusion matrix:')
    print(confusion_matrix(y_n,y_pred))
    print('_ _ _ '*5)
    print('Classification Report:')
    print(classification_report(y_n,y_pred))
    print('_ _ _ '*15)

LogisticRegression()
Confusion matrix:
[[116  31]
 [ 31 116]]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.79      0.79       147
           1       0.79      0.79      0.79       147

    accuracy                           0.79       294
   macro avg       0.79      0.79      0.79       294
weighted avg       0.79      0.79      0.79       294

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
DecisionTreeClassifier()
Confusion matrix:
[[133  14]
 [ 11 136]]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.90      0.91       147
           1       0.91      0.93      0.92       147

    accuracy                           0.91       294
   macro avg       0.92      0.91      0.91       294
weighted avg       0.92      0.91      0.91       294

_ _ _ _ _ _ _ _ _ _

In [20]:
rfc_grid={
    'criterion':['gini','entropy'],
    'n_estimators':[100,150,200],
    'max_depth':[None,10,12,15],
    'min_samples_split':[2,5,10],
    'min_samples_leaf':[1,2,4],
}

In [21]:
rfgscv=GridSearchCV(estimator=RandomForestClassifier(),n_jobs=1,cv=StratifiedKFold(5),verbose=2,param_grid=rfc_grid)

In [22]:
x=x_n
y=y_n

In [23]:
rfgscv.fit(X=x,y=y)

Fitting 5 folds for each of 216 candidates, totalling 1080 fits
[CV] END criterion=gini, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=150; total time=   0.4s
[CV] END criterion=gini, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=150; total time=   0.4s
[CV] END criterion=gini, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=150; tot

[CV] END criterion=gini, max_depth=None, min_samples_leaf=2, min_samples_split=5, n_estimators=150; total time=   0.2s
[CV] END criterion=gini, max_depth=None, min_samples_leaf=2, min_samples_split=5, n_estimators=200; total time=   0.2s
[CV] END criterion=gini, max_depth=None, min_samples_leaf=2, min_samples_split=5, n_estimators=200; total time=   0.3s
[CV] END criterion=gini, max_depth=None, min_samples_leaf=2, min_samples_split=5, n_estimators=200; total time=   0.3s
[CV] END criterion=gini, max_depth=None, min_samples_leaf=2, min_samples_split=5, n_estimators=200; total time=   0.3s
[CV] END criterion=gini, max_depth=None, min_samples_leaf=2, min_samples_split=5, n_estimators=200; total time=   0.3s
[CV] END criterion=gini, max_depth=None, min_samples_leaf=2, min_samples_split=10, n_estimators=100; total time=   0.2s
[CV] END criterion=gini, max_depth=None, min_samples_leaf=2, min_samples_split=10, n_estimators=100; total time=   0.1s
[CV] END criterion=gini, max_depth=None, min_s

[CV] END criterion=gini, max_depth=10, min_samples_leaf=1, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_leaf=1, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_leaf=1, min_samples_split=2, n_estimators=150; total time=   0.2s
[CV] END criterion=gini, max_depth=10, min_samples_leaf=1, min_samples_split=2, n_estimators=150; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_leaf=1, min_samples_split=2, n_estimators=150; total time=   0.3s
[CV] END criterion=gini, max_depth=10, min_samples_leaf=1, min_samples_split=2, n_estimators=150; total time=   0.2s
[CV] END criterion=gini, max_depth=10, min_samples_leaf=1, min_samples_split=2, n_estimators=150; total time=   0.2s
[CV] END criterion=gini, max_depth=10, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   0.5s
[CV] END criterion=gini, max_depth=10, min_samples_leaf=1, min_s

[CV] END criterion=gini, max_depth=10, min_samples_leaf=2, min_samples_split=5, n_estimators=200; total time=   0.3s
[CV] END criterion=gini, max_depth=10, min_samples_leaf=2, min_samples_split=5, n_estimators=200; total time=   0.2s
[CV] END criterion=gini, max_depth=10, min_samples_leaf=2, min_samples_split=10, n_estimators=100; total time=   0.2s
[CV] END criterion=gini, max_depth=10, min_samples_leaf=2, min_samples_split=10, n_estimators=100; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_leaf=2, min_samples_split=10, n_estimators=100; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_leaf=2, min_samples_split=10, n_estimators=100; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_leaf=2, min_samples_split=10, n_estimators=100; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_leaf=2, min_samples_split=10, n_estimators=150; total time=   0.1s
[CV] END criterion=gini, max_depth=10, min_samples_leaf=2,

[CV] END criterion=gini, max_depth=12, min_samples_leaf=1, min_samples_split=2, n_estimators=150; total time=   0.5s
[CV] END criterion=gini, max_depth=12, min_samples_leaf=1, min_samples_split=2, n_estimators=150; total time=   0.4s
[CV] END criterion=gini, max_depth=12, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   0.8s
[CV] END criterion=gini, max_depth=12, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   0.5s
[CV] END criterion=gini, max_depth=12, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   0.2s
[CV] END criterion=gini, max_depth=12, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   0.4s
[CV] END criterion=gini, max_depth=12, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   0.6s
[CV] END criterion=gini, max_depth=12, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   0.2s
[CV] END criterion=gini, max_depth=12, min_samples_leaf=1, min_s

[CV] END criterion=gini, max_depth=12, min_samples_leaf=2, min_samples_split=10, n_estimators=100; total time=   0.0s
[CV] END criterion=gini, max_depth=12, min_samples_leaf=2, min_samples_split=10, n_estimators=100; total time=   0.0s
[CV] END criterion=gini, max_depth=12, min_samples_leaf=2, min_samples_split=10, n_estimators=150; total time=   0.1s
[CV] END criterion=gini, max_depth=12, min_samples_leaf=2, min_samples_split=10, n_estimators=150; total time=   0.2s
[CV] END criterion=gini, max_depth=12, min_samples_leaf=2, min_samples_split=10, n_estimators=150; total time=   0.2s
[CV] END criterion=gini, max_depth=12, min_samples_leaf=2, min_samples_split=10, n_estimators=150; total time=   0.2s
[CV] END criterion=gini, max_depth=12, min_samples_leaf=2, min_samples_split=10, n_estimators=150; total time=   0.1s
[CV] END criterion=gini, max_depth=12, min_samples_leaf=2, min_samples_split=10, n_estimators=200; total time=   0.2s
[CV] END criterion=gini, max_depth=12, min_samples_leaf=

[CV] END criterion=gini, max_depth=15, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   0.2s
[CV] END criterion=gini, max_depth=15, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   0.2s
[CV] END criterion=gini, max_depth=15, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   0.0s
[CV] END criterion=gini, max_depth=15, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   0.1s
[CV] END criterion=gini, max_depth=15, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   0.0s
[CV] END criterion=gini, max_depth=15, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   0.0s
[CV] END criterion=gini, max_depth=15, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   0.1s
[CV] END criterion=gini, max_depth=15, min_samples_leaf=1, min_samples_split=5, n_estimators=150; total time=   0.4s
[CV] END criterion=gini, max_depth=15, min_samples_leaf=1, min_s

[CV] END criterion=gini, max_depth=15, min_samples_leaf=2, min_samples_split=10, n_estimators=150; total time=   0.1s
[CV] END criterion=gini, max_depth=15, min_samples_leaf=2, min_samples_split=10, n_estimators=150; total time=   0.3s
[CV] END criterion=gini, max_depth=15, min_samples_leaf=2, min_samples_split=10, n_estimators=200; total time=   0.6s
[CV] END criterion=gini, max_depth=15, min_samples_leaf=2, min_samples_split=10, n_estimators=200; total time=   0.5s
[CV] END criterion=gini, max_depth=15, min_samples_leaf=2, min_samples_split=10, n_estimators=200; total time=   0.2s
[CV] END criterion=gini, max_depth=15, min_samples_leaf=2, min_samples_split=10, n_estimators=200; total time=   0.2s
[CV] END criterion=gini, max_depth=15, min_samples_leaf=2, min_samples_split=10, n_estimators=200; total time=   0.2s
[CV] END criterion=gini, max_depth=15, min_samples_leaf=4, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=gini, max_depth=15, min_samples_leaf=4

[CV] END criterion=entropy, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=150; total time=   0.3s
[CV] END criterion=entropy, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=150; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=150; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=150; total time=   0.2s
[CV] END criterion=entropy, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=150; total time=   0.3s
[CV] END criterion=entropy, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=200; total time=   0.2s
[CV] END criterion=entropy, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=200; total time=   0.3s
[CV] END criterion=entro

[CV] END criterion=entropy, max_depth=None, min_samples_leaf=2, min_samples_split=10, n_estimators=200; total time=   0.3s
[CV] END criterion=entropy, max_depth=None, min_samples_leaf=2, min_samples_split=10, n_estimators=200; total time=   0.2s
[CV] END criterion=entropy, max_depth=None, min_samples_leaf=2, min_samples_split=10, n_estimators=200; total time=   0.3s
[CV] END criterion=entropy, max_depth=None, min_samples_leaf=2, min_samples_split=10, n_estimators=200; total time=   0.4s
[CV] END criterion=entropy, max_depth=None, min_samples_leaf=4, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_leaf=4, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_leaf=4, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=None, min_samples_leaf=4, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=e

[CV] END criterion=entropy, max_depth=10, min_samples_leaf=1, min_samples_split=5, n_estimators=150; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_leaf=1, min_samples_split=5, n_estimators=150; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_leaf=1, min_samples_split=5, n_estimators=150; total time=   0.2s
[CV] END criterion=entropy, max_depth=10, min_samples_leaf=1, min_samples_split=5, n_estimators=150; total time=   0.2s
[CV] END criterion=entropy, max_depth=10, min_samples_leaf=1, min_samples_split=5, n_estimators=150; total time=   0.4s
[CV] END criterion=entropy, max_depth=10, min_samples_leaf=1, min_samples_split=5, n_estimators=200; total time=   0.6s
[CV] END criterion=entropy, max_depth=10, min_samples_leaf=1, min_samples_split=5, n_estimators=200; total time=   0.4s
[CV] END criterion=entropy, max_depth=10, min_samples_leaf=1, min_samples_split=5, n_estimators=200; total time=   0.3s
[CV] END criterion=entropy, max_depth=10

[CV] END criterion=entropy, max_depth=10, min_samples_leaf=2, min_samples_split=10, n_estimators=200; total time=   0.2s
[CV] END criterion=entropy, max_depth=10, min_samples_leaf=4, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_leaf=4, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_leaf=4, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_leaf=4, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_leaf=4, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=10, min_samples_leaf=4, min_samples_split=2, n_estimators=150; total time=   0.2s
[CV] END criterion=entropy, max_depth=10, min_samples_leaf=4, min_samples_split=2, n_estimators=150; total time=   0.3s
[CV] END criterion=entropy, max_depth=1

[CV] END criterion=entropy, max_depth=12, min_samples_leaf=1, min_samples_split=5, n_estimators=150; total time=   0.2s
[CV] END criterion=entropy, max_depth=12, min_samples_leaf=1, min_samples_split=5, n_estimators=150; total time=   0.1s
[CV] END criterion=entropy, max_depth=12, min_samples_leaf=1, min_samples_split=5, n_estimators=200; total time=   0.2s
[CV] END criterion=entropy, max_depth=12, min_samples_leaf=1, min_samples_split=5, n_estimators=200; total time=   0.2s
[CV] END criterion=entropy, max_depth=12, min_samples_leaf=1, min_samples_split=5, n_estimators=200; total time=   0.2s
[CV] END criterion=entropy, max_depth=12, min_samples_leaf=1, min_samples_split=5, n_estimators=200; total time=   0.5s
[CV] END criterion=entropy, max_depth=12, min_samples_leaf=1, min_samples_split=5, n_estimators=200; total time=   0.5s
[CV] END criterion=entropy, max_depth=12, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   0.2s
[CV] END criterion=entropy, max_depth=1

[CV] END criterion=entropy, max_depth=12, min_samples_leaf=4, min_samples_split=2, n_estimators=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=12, min_samples_leaf=4, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END criterion=entropy, max_depth=12, min_samples_leaf=4, min_samples_split=2, n_estimators=150; total time=   0.2s
[CV] END criterion=entropy, max_depth=12, min_samples_leaf=4, min_samples_split=2, n_estimators=150; total time=   0.2s
[CV] END criterion=entropy, max_depth=12, min_samples_leaf=4, min_samples_split=2, n_estimators=150; total time=   0.4s
[CV] END criterion=entropy, max_depth=12, min_samples_leaf=4, min_samples_split=2, n_estimators=150; total time=   0.4s
[CV] END criterion=entropy, max_depth=12, min_samples_leaf=4, min_samples_split=2, n_estimators=150; total time=   0.4s
[CV] END criterion=entropy, max_depth=12, min_samples_leaf=4, min_samples_split=2, n_estimators=200; total time=   0.4s
[CV] END criterion=entropy, max_depth=12

[CV] END criterion=entropy, max_depth=15, min_samples_leaf=1, min_samples_split=5, n_estimators=200; total time=   0.2s
[CV] END criterion=entropy, max_depth=15, min_samples_leaf=1, min_samples_split=5, n_estimators=200; total time=   0.4s
[CV] END criterion=entropy, max_depth=15, min_samples_leaf=1, min_samples_split=5, n_estimators=200; total time=   0.6s
[CV] END criterion=entropy, max_depth=15, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   0.2s
[CV] END criterion=entropy, max_depth=15, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   0.1s
[CV] END criterion=entropy, max_depth=15, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   0.0s
[CV] END criterion=entropy, max_depth=15, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   0.0s
[CV] END criterion=entropy, max_depth=15, min_samples_leaf=1, min_samples_split=10, n_estimators=100; total time=   0.1s
[CV] END criterion=entropy, max_dep

[CV] END criterion=entropy, max_depth=15, min_samples_leaf=4, min_samples_split=2, n_estimators=150; total time=   0.1s
[CV] END criterion=entropy, max_depth=15, min_samples_leaf=4, min_samples_split=2, n_estimators=150; total time=   0.1s
[CV] END criterion=entropy, max_depth=15, min_samples_leaf=4, min_samples_split=2, n_estimators=150; total time=   0.1s
[CV] END criterion=entropy, max_depth=15, min_samples_leaf=4, min_samples_split=2, n_estimators=150; total time=   0.2s
[CV] END criterion=entropy, max_depth=15, min_samples_leaf=4, min_samples_split=2, n_estimators=200; total time=   0.5s
[CV] END criterion=entropy, max_depth=15, min_samples_leaf=4, min_samples_split=2, n_estimators=200; total time=   0.5s
[CV] END criterion=entropy, max_depth=15, min_samples_leaf=4, min_samples_split=2, n_estimators=200; total time=   0.5s
[CV] END criterion=entropy, max_depth=15, min_samples_leaf=4, min_samples_split=2, n_estimators=200; total time=   0.3s
[CV] END criterion=entropy, max_depth=15

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=RandomForestClassifier(), n_jobs=1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [None, 10, 12, 15],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [100, 150, 200]},
             verbose=2)

In [24]:
rfgscv.best_score_

0.9457042665108123

In [25]:
best_rfc = rfgscv.best_estimator_

In [36]:
y_pred=cross_val_predict(estimator=best_rfc,X=x,y=y,cv=StratifiedKFold(5),n_jobs=-1)
print('Confusion Matrix:\n', confusion_matrix(y, y_pred))
print('_ _ _ ' * 5)
print('Classification Report:\n', classification_report(y, y_pred))

Confusion Matrix:
 [[142   5]
 [ 14 133]]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.97      0.94       147
           1       0.96      0.90      0.93       147

    accuracy                           0.94       294
   macro avg       0.94      0.94      0.94       294
weighted avg       0.94      0.94      0.94       294



In [26]:
xgb_grid = {
    'n_estimators': [50, 100, 200, 300],
    'max_depth': [3, 6, 10, 12],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0],
    'gamma': [0, 0.1, 0.2],
    'reg_alpha': [0, 0.01, 0.1],
    'reg_lambda': [0.01, 0.1, 1.0]
}

In [27]:
xgbgscv = RandomizedSearchCV(estimator=XGBClassifier(),param_distributions=xgb_grid,n_iter=100,cv=StratifiedKFold(5),verbose=2,n_jobs=-1,)

In [28]:
xgbgscv.fit(X=x,y=y)

Fitting 5 folds for each of 100 candidates, totalling 500 fits


RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
                   estimator=XGBClassifier(base_score=None, booster=None,
                                           callbacks=None,
                                           colsample_bylevel=None,
                                           colsample_bynode=None,
                                           colsample_bytree=None, device=None,
                                           early_stopping_rounds=None,
                                           enable_categorical=False,
                                           eval_metric=None, feature_types=None,
                                           gamma=None, grow_policy=None,
                                           impor...
                                           multi_strategy=None,
                                           n_estimators=None, n_jobs=None,
                                           num_parallel_tree=None,
                                           random_state=None, ...),
                   n_iter=100, n_jobs=-1,
                   param_distributions={'colsample_bytree': [0.8, 1.0],
                                        'gamma': [0, 0.1, 0.2],
                                        'learning_rate': [0.01, 0.05, 0.1, 0.2],
                                        'max_depth': [3, 6, 10, 12],
                                        'n_estimators': [50, 100, 200, 300],
                                        'reg_alpha': [0, 0.01, 0.1],
                                        'reg_lambda': [0.01, 0.1, 1.0],
                                        'subsample': [0.8, 1.0]},
                   verbose=2)

In [29]:
xgbgscv.best_score_

0.9457042665108123

In [30]:
best_xgbc = xgbgscv.best_estimator_

In [33]:
y_pred=cross_val_predict(estimator=best_xgbc,X=x,y=y,cv=StratifiedKFold(5),n_jobs=-1)
print('Confusion Matrix:\n', confusion_matrix(y, y_pred))
print('_ _ _ ' * 5)
print('Classification Report:\n', classification_report(y, y_pred))

Confusion Matrix:
 [[143   4]
 [ 12 135]]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.97      0.95       147
           1       0.97      0.92      0.94       147

    accuracy                           0.95       294
   macro avg       0.95      0.95      0.95       294
weighted avg       0.95      0.95      0.95       294



In [37]:
dt_grid = {
    'criterion': ['gini', 'entropy', 'log_loss'],
    'splitter': ['best', 'random'],
    'max_depth': [None, 5, 10, 20, 50],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4, 10],
    'max_features': [None, 'sqrt', 'log2'],
    'ccp_alpha': [0.0, 0.01, 0.1, 1.0]
}

In [38]:
DTgscv = GridSearchCV(estimator=DecisionTreeClassifier(),param_grid=dt_grid,cv=StratifiedKFold(5),n_jobs=-1)

In [39]:
DTgscv.fit(X=x,y=y)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'ccp_alpha': [0.0, 0.01, 0.1, 1.0],
                         'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_depth': [None, 5, 10, 20, 50],
                         'max_features': [None, 'sqrt', 'log2'],
                         'min_samples_leaf': [1, 2, 4, 10],
                         'min_samples_split': [2, 5, 10],
                         'splitter': ['best', 'random']})

In [40]:
DTgscv.best_params_

{'ccp_alpha': 0.0,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'splitter': 'best'}

In [41]:
DTgscv.best_score_

0.9286966686148451

In [43]:
best_dtc= DTgscv.best_estimator_

In [44]:
y_pred=cross_val_predict(estimator=best_dtc,X=x,y=y,cv=StratifiedKFold(5),n_jobs=-1)
print('Confusion Matrix:\n', confusion_matrix(y, y_pred))
print('_ _ _ ' * 5)
print('Classification Report:\n', classification_report(y, y_pred))

Confusion Matrix:
 [[137  10]
 [ 11 136]]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.93      0.93       147
           1       0.93      0.93      0.93       147

    accuracy                           0.93       294
   macro avg       0.93      0.93      0.93       294
weighted avg       0.93      0.93      0.93       294



In [45]:
knn_grid = {
    'n_neighbors': [3, 5, 7, 9, 11, 15],
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan', 'minkowski'],
    'p': [1, 2],
    'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute']
}

In [46]:
KNgscv=GridSearchCV(estimator=KNeighborsClassifier(),n_jobs=-1,verbose=2,param_grid=knn_grid,cv=StratifiedKFold(5))

In [47]:
KNgscv.fit(x,y)

Fitting 5 folds for each of 288 candidates, totalling 1440 fits


GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'metric': ['euclidean', 'manhattan', 'minkowski'],
                         'n_neighbors': [3, 5, 7, 9, 11, 15], 'p': [1, 2],
                         'weights': ['uniform', 'distance']},
             verbose=2)

In [48]:
KNgscv.best_score_

0.8772647574517827

In [49]:
best_knc= KNgscv.best_estimator_

In [50]:
y_pred=cross_val_predict(estimator=best_knc,X=x,y=y,cv=StratifiedKFold(5),n_jobs=-1)
print('Confusion Matrix:\n', confusion_matrix(y, y_pred))
print('_ _ _ ' * 5)
print('Classification Report:\n', classification_report(y, y_pred))

Confusion Matrix:
 [[143   4]
 [ 32 115]]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.97      0.89       147
           1       0.97      0.78      0.86       147

    accuracy                           0.88       294
   macro avg       0.89      0.88      0.88       294
weighted avg       0.89      0.88      0.88       294



In [71]:
voting_clf=VotingClassifier(
    estimators=[
        ('XGBoost',best_xgbc),
        ('RandomForest',best_rfc),
        ('KNeighbors',best_knc),
        ('DecisionTree',best_dtc)
    ]
    ,voting='soft')

In [81]:
y_pred_voting=cross_val_predict(estimator=voting_clf,X=x,y=y,cv=StratifiedKFold(5),n_jobs=-1)
print('Confusion Matrix:\n', confusion_matrix(y, y_pred_voting))
print('_ _ _ ' * 5)
print('Classification Report:\n', classification_report(y, y_pred_voting))

Confusion Matrix:
 [[141   6]
 [  9 138]]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Classification Report:
               precision    recall  f1-score   support

           0       0.94      0.96      0.95       147
           1       0.96      0.94      0.95       147

    accuracy                           0.95       294
   macro avg       0.95      0.95      0.95       294
weighted avg       0.95      0.95      0.95       294



Conclusion:
achived an accuracy of 95% using Voting classifier